# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: earendil <earendil@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/05/29 12:15:29 by mmarinel          #+#    #+#              #
#    Updated: 2023/06/02 12:51:30 by earendil         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	g++ -Wall -Werror -Wextra mini_serv.cpp ConnectionSocket.cpp SocketStream.cpp EpollData.cpp -o mini_serv

clean:
	rm -rf mini_serv