# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mmarinel <mmarinel@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/05/29 12:15:29 by mmarinel          #+#    #+#              #
#    Updated: 2023/05/30 17:07:33 by mmarinel         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	g++ -Wall -Werror -Wextra mini_serv.cpp ConnectionSocket.cpp SocketStream.cpp -o mini_serv

clean:
	rm -rf mini_serv